### ISSUE TITLE
Discussion around `droidboot_ret` typedef.

### ISSUE THREAD

**Issue by shymega** [Android-Boot-Manager/droidboot_gui#1]
(Couldn't find the Discussions tab)

Whilst I wait to be able to push my latest commit, which will use an enum for errors, I thought we should discuss the typedef for `droidboot_ret` [here](https://github.com/Android-Boot-Manager/droidboot_gui/blob/main/include/droidboot_error.h#L3) - if we use the `droidboot_error` as seen on f16c296 (when pushed), then there'll be no need for the custom `droidboot_ret` type.

Thoughts?

**Comment by shymega** [comment]
No wait, never mind. I see where the thinking is now. We want to use `int` for the return type, and the `droidboot_error` enum has `int` type values anyway, so this works just fine. I'm being an idiot. Sometimes reading code twice before an issue opens helps wonders.

**Comment by nift4** [comment]
> Couldn't find the Discussions tab

Use the telegram group :)
In my opinion its better than having discussions scattered everywhere around the place

**Comment by shymega** [comment]
The problem with the TG group is that it's not structured. We can use it for quick questions like #1, I suppose, but we should really start discussing design on GitHub. Our TG group is just too cluttered, and hard to find the 'right info' quickly. We could also create issues with the `good first issue` label as well which would attract interest...

**Comment by nift4** [comment]
In my opinion, if we arent more than 5 people, it's not worth it. Chat is just quicker

**Comment by shymega** [comment]
Sure, but even on small GitHub projects, it's good practice to use the tools provided. Chat can get messy, and it's best to structure these things. And yeah, I need to get the wiki going 😅

**Comment by nift4** [comment]
@shymega I just dont like the duality of two mediums used to communicate

**Comment by luka177** [comment]
@shymega lets do fucking product instead of fucking with gh😂
